/**
 * The 100 jobs from dataset/mldataset.xlsx (the capstone TF-IDF dataset), mapped onto the app's Job
 * shape by scripts/map_mldataset_jobs.py + scripts/import-mldataset-jobs.ts. IDs continue from the
 * 13 curated demo jobs in data.ts (JOB-001..JOB-013) at JOB-014..JOB-113, so they never collide.
 *
 * Regenerate: python scripts/map_mldataset_jobs.py && npx tsx scripts/import-mldataset-jobs.ts
 */
import type { Job } from './data'

export const mldatasetJobs: Job[] = [
  {
    "id": "JOB-014",
    "title": "Data Entry Clerk",
    "company": "Los Baños Records Office",
    "description": "Encoding documents, organizing files, spreadsheet use",
    "location": "Los Baños, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "typing",
      "data entry",
      "Microsoft Office",
      "communication"
    ],
    "minEducation": "College Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-10-27",
    "status": "Open",
    "postedDate": "2026-08-21",
    "category": "Administrative"
  },
  {
    "id": "JOB-015",
    "title": "Customer Service Representative",
    "company": "Calamba Customer Care Center",
    "description": "Answering inquiries, resolving concerns, assisting customers",
    "location": "Calamba, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "customer service",
      "communication",
      "computer skills",
      "English"
    ],
    "minEducation": "High School Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-19",
    "status": "Open",
    "postedDate": "2026-07-06",
    "category": "Customer Service"
  },
  {
    "id": "JOB-016",
    "title": "Graphic Designer",
    "company": "Santa Rosa Design Studio",
    "description": "Creating posters, editing images, social media graphics",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "graphic design",
      "Canva",
      "Photoshop",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-10-03",
    "status": "Open",
    "postedDate": "2026-06-18",
    "category": "Creative"
  },
  {
    "id": "JOB-017",
    "title": "Kitchen Assistant",
    "company": "Bay Kitchen & Catering Services",
    "description": "Food preparation, cleaning, kitchen assistance",
    "location": "Bay, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "cooking",
      "food preparation",
      "cleanliness",
      "teamwork"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-12-11",
    "status": "Open",
    "postedDate": "2026-08-26",
    "category": "Food Service"
  },
  {
    "id": "JOB-018",
    "title": "Junior Web Developer",
    "company": "Biñan Web Solutions",
    "description": "Creating webpages, website editing, basic coding",
    "location": "Biñan, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "HTML",
      "CSS",
      "JavaScript",
      "web development"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-11-10",
    "status": "Open",
    "postedDate": "2026-08-15",
    "category": "Technical"
  },
  {
    "id": "JOB-019",
    "title": "Accounting Assistant",
    "company": "Los Baños Accounting Office",
    "description": "Recording transactions, spreadsheets, filing",
    "location": "Los Baños, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "Excel",
      "bookkeeping",
      "accounting",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-08-08",
    "status": "Open",
    "postedDate": "2026-06-04",
    "category": "Administrative"
  },
  {
    "id": "JOB-020",
    "title": "Content Writer",
    "company": "Calamba Media Group",
    "description": "Writing articles, researching, proofreading",
    "location": "Calamba, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "writing",
      "English",
      "research",
      "proofreading"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-09-30",
    "status": "Open",
    "postedDate": "2026-06-30",
    "category": "Creative"
  },
  {
    "id": "JOB-021",
    "title": "Social Media Assistant",
    "company": "Santa Rosa Digital Marketing Agency",
    "description": "Creating posts, managing pages, digital content",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "social media",
      "Canva",
      "communication",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-10-22",
    "status": "Open",
    "postedDate": "2026-08-11",
    "category": "Creative"
  },
  {
    "id": "JOB-022",
    "title": "Inventory Assistant",
    "company": "Bay Trading Company",
    "description": "Recording stocks, checking inventory, updating records",
    "location": "Bay, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "inventory",
      "Excel",
      "organization",
      "record keeping"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-09-25",
    "status": "Open",
    "postedDate": "2026-06-29",
    "category": "Administrative"
  },
  {
    "id": "JOB-023",
    "title": "Online Tutor",
    "company": "Biñan Learning Center",
    "description": "Online lessons, explaining topics, preparing materials",
    "location": "Biñan, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "teaching",
      "communication",
      "patience",
      "English"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-17",
    "status": "Open",
    "postedDate": "2026-06-01",
    "category": "Education"
  },
  {
    "id": "JOB-024",
    "title": "Administrative Assistant",
    "company": "Los Baños Business Center",
    "description": "Document preparation, filing, data entry",
    "location": "Los Baños, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "typing",
      "Word",
      "Excel",
      "filing",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-11-24",
    "status": "Open",
    "postedDate": "2026-08-29",
    "category": "Administrative"
  },
  {
    "id": "JOB-025",
    "title": "Sales Assistant",
    "company": "Calamba Retail Store",
    "description": "Assisting customers, explaining products, processing sales",
    "location": "Calamba, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "sales",
      "communication",
      "customer service",
      "persuasion"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-13",
    "status": "Open",
    "postedDate": "2026-07-06",
    "category": "Customer Service"
  },
  {
    "id": "JOB-026",
    "title": "Photo Editor",
    "company": "Santa Rosa Photo Studio",
    "description": "Editing photographs, enhancing images, organizing media",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "photography",
      "photo editing",
      "Photoshop",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-09-18",
    "status": "Open",
    "postedDate": "2026-07-14",
    "category": "Creative"
  },
  {
    "id": "JOB-027",
    "title": "Bookkeeping Assistant",
    "company": "Bay Bookkeeping Services",
    "description": "Recording transactions, organizing financial records",
    "location": "Bay, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "bookkeeping",
      "Excel",
      "organization",
      "mathematics"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-09-23",
    "status": "Open",
    "postedDate": "2026-07-19",
    "category": "Administrative"
  },
  {
    "id": "JOB-028",
    "title": "Office Assistant",
    "company": "Biñan Business Solutions",
    "description": "Email handling, encoding documents, file organization",
    "location": "Biñan, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "computer literacy",
      "typing",
      "communication",
      "email"
    ],
    "minEducation": "College Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-10-21",
    "status": "Open",
    "postedDate": "2026-07-15",
    "category": "Administrative"
  },
  {
    "id": "JOB-029",
    "title": "Junior Programmer",
    "company": "Los Baños Software Solutions",
    "description": "Writing basic programs, debugging, testing applications",
    "location": "Los Baños, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "programming",
      "Python",
      "Java",
      "problem solving"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-09-20",
    "status": "Open",
    "postedDate": "2026-06-06",
    "category": "Technical"
  },
  {
    "id": "JOB-030",
    "title": "Customer Support Agent",
    "company": "Calamba Support Center",
    "description": "Handling inquiries, providing support, documenting concerns",
    "location": "Calamba, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "customer service",
      "English",
      "communication",
      "patience"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-10-14",
    "status": "Open",
    "postedDate": "2026-08-08",
    "category": "Customer Service"
  },
  {
    "id": "JOB-031",
    "title": "Bakery Assistant",
    "company": "Santa Rosa Bakeshop",
    "description": "Baking assistance, ingredient preparation, cleaning",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "baking",
      "food preparation",
      "teamwork",
      "cleanliness"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-09-14",
    "status": "Open",
    "postedDate": "2026-06-11",
    "category": "Food Service"
  },
  {
    "id": "JOB-032",
    "title": "Research Assistant",
    "company": "Bay Research Institute",
    "description": "Online research, organizing information, preparing reports",
    "location": "Bay, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "writing",
      "research",
      "Word",
      "proofreading"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-11-27",
    "status": "Open",
    "postedDate": "2026-08-20",
    "category": "Education"
  },
  {
    "id": "JOB-033",
    "title": "Inventory Clerk",
    "company": "Biñan Trading Company",
    "description": "Recording products, updating inventory databases, stock records",
    "location": "Biñan, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "Excel",
      "inventory",
      "typing",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-10-24",
    "status": "Open",
    "postedDate": "2026-08-13",
    "category": "Administrative"
  },
  {
    "id": "JOB-034",
    "title": "Data Entry Clerk",
    "company": "Los Baños Records Office",
    "description": "Encoding documents, organizing files, spreadsheet use",
    "location": "Los Baños, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "typing",
      "data entry",
      "Microsoft Office",
      "communication"
    ],
    "minEducation": "College Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-16",
    "status": "Open",
    "postedDate": "2026-06-06",
    "category": "Administrative"
  },
  {
    "id": "JOB-035",
    "title": "Customer Service Representative",
    "company": "Calamba Customer Care Center",
    "description": "Answering inquiries, resolving concerns, assisting customers",
    "location": "Calamba, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "customer service",
      "communication",
      "computer skills",
      "English"
    ],
    "minEducation": "High School Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-11",
    "status": "Open",
    "postedDate": "2026-07-08",
    "category": "Customer Service"
  },
  {
    "id": "JOB-036",
    "title": "Graphic Designer",
    "company": "Santa Rosa Design Studio",
    "description": "Creating posters, editing images, social media graphics",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "graphic design",
      "Canva",
      "Photoshop",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-09-05",
    "status": "Open",
    "postedDate": "2026-06-13",
    "category": "Creative"
  },
  {
    "id": "JOB-037",
    "title": "Kitchen Assistant",
    "company": "Bay Kitchen & Catering Services",
    "description": "Food preparation, cleaning, kitchen assistance",
    "location": "Bay, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "cooking",
      "food preparation",
      "cleanliness",
      "teamwork"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-11-06",
    "status": "Open",
    "postedDate": "2026-07-29",
    "category": "Food Service"
  },
  {
    "id": "JOB-038",
    "title": "Junior Web Developer",
    "company": "Biñan Web Solutions",
    "description": "Creating webpages, website editing, basic coding",
    "location": "Biñan, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "HTML",
      "CSS",
      "JavaScript",
      "web development"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-09-12",
    "status": "Open",
    "postedDate": "2026-06-21",
    "category": "Technical"
  },
  {
    "id": "JOB-039",
    "title": "Accounting Assistant",
    "company": "Los Baños Accounting Office",
    "description": "Recording transactions, spreadsheets, filing",
    "location": "Los Baños, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "Excel",
      "bookkeeping",
      "accounting",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-10-07",
    "status": "Open",
    "postedDate": "2026-06-27",
    "category": "Administrative"
  },
  {
    "id": "JOB-040",
    "title": "Content Writer",
    "company": "Calamba Media Group",
    "description": "Writing articles, researching, proofreading",
    "location": "Calamba, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "writing",
      "English",
      "research",
      "proofreading"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-12-26",
    "status": "Open",
    "postedDate": "2026-08-29",
    "category": "Creative"
  },
  {
    "id": "JOB-041",
    "title": "Social Media Assistant",
    "company": "Santa Rosa Digital Marketing Agency",
    "description": "Creating posts, managing pages, digital content",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "social media",
      "Canva",
      "communication",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-11-25",
    "status": "Open",
    "postedDate": "2026-08-17",
    "category": "Creative"
  },
  {
    "id": "JOB-042",
    "title": "Inventory Assistant",
    "company": "Bay Trading Company",
    "description": "Recording stocks, checking inventory, updating records",
    "location": "Bay, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "inventory",
      "Excel",
      "organization",
      "record keeping"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-11-22",
    "status": "Open",
    "postedDate": "2026-08-08",
    "category": "Administrative"
  },
  {
    "id": "JOB-043",
    "title": "Online Tutor",
    "company": "Biñan Learning Center",
    "description": "Online lessons, explaining topics, preparing materials",
    "location": "Biñan, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "teaching",
      "communication",
      "patience",
      "English"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-09-18",
    "status": "Open",
    "postedDate": "2026-06-21",
    "category": "Education"
  },
  {
    "id": "JOB-044",
    "title": "Administrative Assistant",
    "company": "Los Baños Business Center",
    "description": "Document preparation, filing, data entry",
    "location": "Los Baños, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "typing",
      "Word",
      "Excel",
      "filing",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-11-01",
    "status": "Open",
    "postedDate": "2026-07-05",
    "category": "Administrative"
  },
  {
    "id": "JOB-045",
    "title": "Sales Assistant",
    "company": "Calamba Retail Store",
    "description": "Assisting customers, explaining products, processing sales",
    "location": "Calamba, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "sales",
      "communication",
      "customer service",
      "persuasion"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-11-15",
    "status": "Open",
    "postedDate": "2026-08-27",
    "category": "Customer Service"
  },
  {
    "id": "JOB-046",
    "title": "Photo Editor",
    "company": "Santa Rosa Photo Studio",
    "description": "Editing photographs, enhancing images, organizing media",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "photography",
      "photo editing",
      "Photoshop",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-10-20",
    "status": "Open",
    "postedDate": "2026-06-30",
    "category": "Creative"
  },
  {
    "id": "JOB-047",
    "title": "Bookkeeping Assistant",
    "company": "Bay Bookkeeping Services",
    "description": "Recording transactions, organizing financial records",
    "location": "Bay, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "bookkeeping",
      "Excel",
      "organization",
      "mathematics"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-10-04",
    "status": "Open",
    "postedDate": "2026-07-11",
    "category": "Administrative"
  },
  {
    "id": "JOB-048",
    "title": "Office Assistant",
    "company": "Biñan Business Solutions",
    "description": "Email handling, encoding documents, file organization",
    "location": "Biñan, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "computer literacy",
      "typing",
      "communication",
      "email"
    ],
    "minEducation": "College Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-08-21",
    "status": "Open",
    "postedDate": "2026-06-09",
    "category": "Administrative"
  },
  {
    "id": "JOB-049",
    "title": "Junior Programmer",
    "company": "Los Baños Software Solutions",
    "description": "Writing basic programs, debugging, testing applications",
    "location": "Los Baños, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "programming",
      "Python",
      "Java",
      "problem solving"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-10-07",
    "status": "Open",
    "postedDate": "2026-06-28",
    "category": "Technical"
  },
  {
    "id": "JOB-050",
    "title": "Customer Support Agent",
    "company": "Calamba Support Center",
    "description": "Handling inquiries, providing support, documenting concerns",
    "location": "Calamba, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "customer service",
      "English",
      "communication",
      "patience"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-11-14",
    "status": "Open",
    "postedDate": "2026-07-21",
    "category": "Customer Service"
  },
  {
    "id": "JOB-051",
    "title": "Bakery Assistant",
    "company": "Santa Rosa Bakeshop",
    "description": "Baking assistance, ingredient preparation, cleaning",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "baking",
      "food preparation",
      "teamwork",
      "cleanliness"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-03",
    "status": "Open",
    "postedDate": "2026-06-19",
    "category": "Food Service"
  },
  {
    "id": "JOB-052",
    "title": "Research Assistant",
    "company": "Bay Research Institute",
    "description": "Online research, organizing information, preparing reports",
    "location": "Bay, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "writing",
      "research",
      "Word",
      "proofreading"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-10-17",
    "status": "Open",
    "postedDate": "2026-07-02",
    "category": "Education"
  },
  {
    "id": "JOB-053",
    "title": "Inventory Clerk",
    "company": "Biñan Trading Company",
    "description": "Recording products, updating inventory databases, stock records",
    "location": "Biñan, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "Excel",
      "inventory",
      "typing",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-11-09",
    "status": "Open",
    "postedDate": "2026-08-14",
    "category": "Administrative"
  },
  {
    "id": "JOB-054",
    "title": "Data Entry Clerk",
    "company": "Los Baños Records Office",
    "description": "Encoding documents, organizing files, spreadsheet use",
    "location": "Los Baños, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "typing",
      "data entry",
      "Microsoft Office",
      "communication"
    ],
    "minEducation": "College Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-29",
    "status": "Open",
    "postedDate": "2026-07-17",
    "category": "Administrative"
  },
  {
    "id": "JOB-055",
    "title": "Customer Service Representative",
    "company": "Calamba Customer Care Center",
    "description": "Answering inquiries, resolving concerns, assisting customers",
    "location": "Calamba, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "customer service",
      "communication",
      "computer skills",
      "English"
    ],
    "minEducation": "High School Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-11-04",
    "status": "Open",
    "postedDate": "2026-08-05",
    "category": "Customer Service"
  },
  {
    "id": "JOB-056",
    "title": "Graphic Designer",
    "company": "Santa Rosa Design Studio",
    "description": "Creating posters, editing images, social media graphics",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "graphic design",
      "Canva",
      "Photoshop",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-09-30",
    "status": "Open",
    "postedDate": "2026-06-07",
    "category": "Creative"
  },
  {
    "id": "JOB-057",
    "title": "Kitchen Assistant",
    "company": "Bay Kitchen & Catering Services",
    "description": "Food preparation, cleaning, kitchen assistance",
    "location": "Bay, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "cooking",
      "food preparation",
      "cleanliness",
      "teamwork"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-28",
    "status": "Open",
    "postedDate": "2026-06-20",
    "category": "Food Service"
  },
  {
    "id": "JOB-058",
    "title": "Junior Web Developer",
    "company": "Biñan Web Solutions",
    "description": "Creating webpages, website editing, basic coding",
    "location": "Biñan, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "HTML",
      "CSS",
      "JavaScript",
      "web development"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-11-22",
    "status": "Open",
    "postedDate": "2026-08-27",
    "category": "Technical"
  },
  {
    "id": "JOB-059",
    "title": "Accounting Assistant",
    "company": "Los Baños Accounting Office",
    "description": "Recording transactions, spreadsheets, filing",
    "location": "Los Baños, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "Excel",
      "bookkeeping",
      "accounting",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-10-12",
    "status": "Open",
    "postedDate": "2026-07-20",
    "category": "Administrative"
  },
  {
    "id": "JOB-060",
    "title": "Content Writer",
    "company": "Calamba Media Group",
    "description": "Writing articles, researching, proofreading",
    "location": "Calamba, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "writing",
      "English",
      "research",
      "proofreading"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-10-22",
    "status": "Open",
    "postedDate": "2026-08-07",
    "category": "Creative"
  },
  {
    "id": "JOB-061",
    "title": "Social Media Assistant",
    "company": "Santa Rosa Digital Marketing Agency",
    "description": "Creating posts, managing pages, digital content",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "social media",
      "Canva",
      "communication",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-12-11",
    "status": "Open",
    "postedDate": "2026-08-27",
    "category": "Creative"
  },
  {
    "id": "JOB-062",
    "title": "Inventory Assistant",
    "company": "Bay Trading Company",
    "description": "Recording stocks, checking inventory, updating records",
    "location": "Bay, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "inventory",
      "Excel",
      "organization",
      "record keeping"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-12-21",
    "status": "Open",
    "postedDate": "2026-08-27",
    "category": "Administrative"
  },
  {
    "id": "JOB-063",
    "title": "Online Tutor",
    "company": "Biñan Learning Center",
    "description": "Online lessons, explaining topics, preparing materials",
    "location": "Biñan, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "teaching",
      "communication",
      "patience",
      "English"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-11-11",
    "status": "Open",
    "postedDate": "2026-08-22",
    "category": "Education"
  },
  {
    "id": "JOB-064",
    "title": "Administrative Assistant",
    "company": "Los Baños Business Center",
    "description": "Document preparation, filing, data entry",
    "location": "Los Baños, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "typing",
      "Word",
      "Excel",
      "filing",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-10-03",
    "status": "Open",
    "postedDate": "2026-07-08",
    "category": "Administrative"
  },
  {
    "id": "JOB-065",
    "title": "Sales Assistant",
    "company": "Calamba Retail Store",
    "description": "Assisting customers, explaining products, processing sales",
    "location": "Calamba, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "sales",
      "communication",
      "customer service",
      "persuasion"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-09-27",
    "status": "Open",
    "postedDate": "2026-07-29",
    "category": "Customer Service"
  },
  {
    "id": "JOB-066",
    "title": "Photo Editor",
    "company": "Santa Rosa Photo Studio",
    "description": "Editing photographs, enhancing images, organizing media",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "photography",
      "photo editing",
      "Photoshop",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-11-20",
    "status": "Open",
    "postedDate": "2026-08-04",
    "category": "Creative"
  },
  {
    "id": "JOB-067",
    "title": "Bookkeeping Assistant",
    "company": "Bay Bookkeeping Services",
    "description": "Recording transactions, organizing financial records",
    "location": "Bay, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "bookkeeping",
      "Excel",
      "organization",
      "mathematics"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-11-30",
    "status": "Open",
    "postedDate": "2026-08-04",
    "category": "Administrative"
  },
  {
    "id": "JOB-068",
    "title": "Office Assistant",
    "company": "Biñan Business Solutions",
    "description": "Email handling, encoding documents, file organization",
    "location": "Biñan, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "computer literacy",
      "typing",
      "communication",
      "email"
    ],
    "minEducation": "College Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-11-07",
    "status": "Open",
    "postedDate": "2026-08-20",
    "category": "Administrative"
  },
  {
    "id": "JOB-069",
    "title": "Junior Programmer",
    "company": "Los Baños Software Solutions",
    "description": "Writing basic programs, debugging, testing applications",
    "location": "Los Baños, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "programming",
      "Python",
      "Java",
      "problem solving"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-11",
    "status": "Open",
    "postedDate": "2026-06-20",
    "category": "Technical"
  },
  {
    "id": "JOB-070",
    "title": "Customer Support Agent",
    "company": "Calamba Support Center",
    "description": "Handling inquiries, providing support, documenting concerns",
    "location": "Calamba, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "customer service",
      "English",
      "communication",
      "patience"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-11-26",
    "status": "Open",
    "postedDate": "2026-08-09",
    "category": "Customer Service"
  },
  {
    "id": "JOB-071",
    "title": "Bakery Assistant",
    "company": "Santa Rosa Bakeshop",
    "description": "Baking assistance, ingredient preparation, cleaning",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "baking",
      "food preparation",
      "teamwork",
      "cleanliness"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-11-04",
    "status": "Open",
    "postedDate": "2026-08-16",
    "category": "Food Service"
  },
  {
    "id": "JOB-072",
    "title": "Research Assistant",
    "company": "Bay Research Institute",
    "description": "Online research, organizing information, preparing reports",
    "location": "Bay, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "writing",
      "research",
      "Word",
      "proofreading"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-08-09",
    "status": "Open",
    "postedDate": "2026-06-03",
    "category": "Education"
  },
  {
    "id": "JOB-073",
    "title": "Inventory Clerk",
    "company": "Biñan Trading Company",
    "description": "Recording products, updating inventory databases, stock records",
    "location": "Biñan, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "Excel",
      "inventory",
      "typing",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-09-23",
    "status": "Open",
    "postedDate": "2026-07-10",
    "category": "Administrative"
  },
  {
    "id": "JOB-074",
    "title": "Data Entry Clerk",
    "company": "Los Baños Records Office",
    "description": "Encoding documents, organizing files, spreadsheet use",
    "location": "Los Baños, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "typing",
      "data entry",
      "Microsoft Office",
      "communication"
    ],
    "minEducation": "College Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-10-25",
    "status": "Open",
    "postedDate": "2026-07-01",
    "category": "Administrative"
  },
  {
    "id": "JOB-075",
    "title": "Customer Service Representative",
    "company": "Calamba Customer Care Center",
    "description": "Answering inquiries, resolving concerns, assisting customers",
    "location": "Calamba, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "customer service",
      "communication",
      "computer skills",
      "English"
    ],
    "minEducation": "High School Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-09-25",
    "status": "Open",
    "postedDate": "2026-06-11",
    "category": "Customer Service"
  },
  {
    "id": "JOB-076",
    "title": "Graphic Designer",
    "company": "Santa Rosa Design Studio",
    "description": "Creating posters, editing images, social media graphics",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "graphic design",
      "Canva",
      "Photoshop",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-25",
    "status": "Open",
    "postedDate": "2026-06-09",
    "category": "Creative"
  },
  {
    "id": "JOB-077",
    "title": "Kitchen Assistant",
    "company": "Bay Kitchen & Catering Services",
    "description": "Food preparation, cleaning, kitchen assistance",
    "location": "Bay, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "cooking",
      "food preparation",
      "cleanliness",
      "teamwork"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-09-27",
    "status": "Open",
    "postedDate": "2026-06-17",
    "category": "Food Service"
  },
  {
    "id": "JOB-078",
    "title": "Junior Web Developer",
    "company": "Biñan Web Solutions",
    "description": "Creating webpages, website editing, basic coding",
    "location": "Biñan, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "HTML",
      "CSS",
      "JavaScript",
      "web development"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-10-19",
    "status": "Open",
    "postedDate": "2026-08-10",
    "category": "Technical"
  },
  {
    "id": "JOB-079",
    "title": "Accounting Assistant",
    "company": "Los Baños Accounting Office",
    "description": "Recording transactions, spreadsheets, filing",
    "location": "Los Baños, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "Excel",
      "bookkeeping",
      "accounting",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-11-30",
    "status": "Open",
    "postedDate": "2026-08-07",
    "category": "Administrative"
  },
  {
    "id": "JOB-080",
    "title": "Content Writer",
    "company": "Calamba Media Group",
    "description": "Writing articles, researching, proofreading",
    "location": "Calamba, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "writing",
      "English",
      "research",
      "proofreading"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-10-25",
    "status": "Open",
    "postedDate": "2026-06-28",
    "category": "Creative"
  },
  {
    "id": "JOB-081",
    "title": "Social Media Assistant",
    "company": "Santa Rosa Digital Marketing Agency",
    "description": "Creating posts, managing pages, digital content",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "social media",
      "Canva",
      "communication",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-10-03",
    "status": "Open",
    "postedDate": "2026-07-10",
    "category": "Creative"
  },
  {
    "id": "JOB-082",
    "title": "Inventory Assistant",
    "company": "Bay Trading Company",
    "description": "Recording stocks, checking inventory, updating records",
    "location": "Bay, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "inventory",
      "Excel",
      "organization",
      "record keeping"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-11-21",
    "status": "Open",
    "postedDate": "2026-07-27",
    "category": "Administrative"
  },
  {
    "id": "JOB-083",
    "title": "Online Tutor",
    "company": "Biñan Learning Center",
    "description": "Online lessons, explaining topics, preparing materials",
    "location": "Biñan, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "teaching",
      "communication",
      "patience",
      "English"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-08-30",
    "status": "Open",
    "postedDate": "2026-06-16",
    "category": "Education"
  },
  {
    "id": "JOB-084",
    "title": "Administrative Assistant",
    "company": "Los Baños Business Center",
    "description": "Document preparation, filing, data entry",
    "location": "Los Baños, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "typing",
      "Word",
      "Excel",
      "filing",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-08-29",
    "status": "Open",
    "postedDate": "2026-06-09",
    "category": "Administrative"
  },
  {
    "id": "JOB-085",
    "title": "Sales Assistant",
    "company": "Calamba Retail Store",
    "description": "Assisting customers, explaining products, processing sales",
    "location": "Calamba, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "sales",
      "communication",
      "customer service",
      "persuasion"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-11-18",
    "status": "Open",
    "postedDate": "2026-08-15",
    "category": "Customer Service"
  },
  {
    "id": "JOB-086",
    "title": "Photo Editor",
    "company": "Santa Rosa Photo Studio",
    "description": "Editing photographs, enhancing images, organizing media",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "photography",
      "photo editing",
      "Photoshop",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-10-28",
    "status": "Open",
    "postedDate": "2026-08-15",
    "category": "Creative"
  },
  {
    "id": "JOB-087",
    "title": "Bookkeeping Assistant",
    "company": "Bay Bookkeeping Services",
    "description": "Recording transactions, organizing financial records",
    "location": "Bay, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "bookkeeping",
      "Excel",
      "organization",
      "mathematics"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-09-23",
    "status": "Open",
    "postedDate": "2026-06-10",
    "category": "Administrative"
  },
  {
    "id": "JOB-088",
    "title": "Office Assistant",
    "company": "Biñan Business Solutions",
    "description": "Email handling, encoding documents, file organization",
    "location": "Biñan, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "computer literacy",
      "typing",
      "communication",
      "email"
    ],
    "minEducation": "College Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-09-02",
    "status": "Open",
    "postedDate": "2026-06-30",
    "category": "Administrative"
  },
  {
    "id": "JOB-089",
    "title": "Junior Programmer",
    "company": "Los Baños Software Solutions",
    "description": "Writing basic programs, debugging, testing applications",
    "location": "Los Baños, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "programming",
      "Python",
      "Java",
      "problem solving"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-15",
    "status": "Open",
    "postedDate": "2026-07-13",
    "category": "Technical"
  },
  {
    "id": "JOB-090",
    "title": "Customer Support Agent",
    "company": "Calamba Support Center",
    "description": "Handling inquiries, providing support, documenting concerns",
    "location": "Calamba, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "customer service",
      "English",
      "communication",
      "patience"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-10-16",
    "status": "Open",
    "postedDate": "2026-07-06",
    "category": "Customer Service"
  },
  {
    "id": "JOB-091",
    "title": "Bakery Assistant",
    "company": "Santa Rosa Bakeshop",
    "description": "Baking assistance, ingredient preparation, cleaning",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "baking",
      "food preparation",
      "teamwork",
      "cleanliness"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-30",
    "status": "Open",
    "postedDate": "2026-06-28",
    "category": "Food Service"
  },
  {
    "id": "JOB-092",
    "title": "Research Assistant",
    "company": "Bay Research Institute",
    "description": "Online research, organizing information, preparing reports",
    "location": "Bay, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "writing",
      "research",
      "Word",
      "proofreading"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-11-17",
    "status": "Open",
    "postedDate": "2026-08-13",
    "category": "Education"
  },
  {
    "id": "JOB-093",
    "title": "Inventory Clerk",
    "company": "Biñan Trading Company",
    "description": "Recording products, updating inventory databases, stock records",
    "location": "Biñan, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "Excel",
      "inventory",
      "typing",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-10-20",
    "status": "Open",
    "postedDate": "2026-07-02",
    "category": "Administrative"
  },
  {
    "id": "JOB-094",
    "title": "Data Entry Clerk",
    "company": "Los Baños Records Office",
    "description": "Encoding documents, organizing files, spreadsheet use",
    "location": "Los Baños, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "typing",
      "data entry",
      "Microsoft Office",
      "communication"
    ],
    "minEducation": "College Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-10-03",
    "status": "Open",
    "postedDate": "2026-07-23",
    "category": "Administrative"
  },
  {
    "id": "JOB-095",
    "title": "Customer Service Representative",
    "company": "Calamba Customer Care Center",
    "description": "Answering inquiries, resolving concerns, assisting customers",
    "location": "Calamba, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "customer service",
      "communication",
      "computer skills",
      "English"
    ],
    "minEducation": "High School Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-09-23",
    "status": "Open",
    "postedDate": "2026-06-13",
    "category": "Customer Service"
  },
  {
    "id": "JOB-096",
    "title": "Graphic Designer",
    "company": "Santa Rosa Design Studio",
    "description": "Creating posters, editing images, social media graphics",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "graphic design",
      "Canva",
      "Photoshop",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-10-11",
    "status": "Open",
    "postedDate": "2026-07-16",
    "category": "Creative"
  },
  {
    "id": "JOB-097",
    "title": "Kitchen Assistant",
    "company": "Bay Kitchen & Catering Services",
    "description": "Food preparation, cleaning, kitchen assistance",
    "location": "Bay, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "cooking",
      "food preparation",
      "cleanliness",
      "teamwork"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-11-22",
    "status": "Open",
    "postedDate": "2026-07-30",
    "category": "Food Service"
  },
  {
    "id": "JOB-098",
    "title": "Junior Web Developer",
    "company": "Biñan Web Solutions",
    "description": "Creating webpages, website editing, basic coding",
    "location": "Biñan, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "HTML",
      "CSS",
      "JavaScript",
      "web development"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-12-05",
    "status": "Open",
    "postedDate": "2026-08-26",
    "category": "Technical"
  },
  {
    "id": "JOB-099",
    "title": "Accounting Assistant",
    "company": "Los Baños Accounting Office",
    "description": "Recording transactions, spreadsheets, filing",
    "location": "Los Baños, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "Excel",
      "bookkeeping",
      "accounting",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-09-01",
    "status": "Open",
    "postedDate": "2026-06-08",
    "category": "Administrative"
  },
  {
    "id": "JOB-100",
    "title": "Content Writer",
    "company": "Calamba Media Group",
    "description": "Writing articles, researching, proofreading",
    "location": "Calamba, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "writing",
      "English",
      "research",
      "proofreading"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-08-28",
    "status": "Open",
    "postedDate": "2026-06-14",
    "category": "Creative"
  },
  {
    "id": "JOB-101",
    "title": "Social Media Assistant",
    "company": "Santa Rosa Digital Marketing Agency",
    "description": "Creating posts, managing pages, digital content",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "social media",
      "Canva",
      "communication",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-09-27",
    "status": "Open",
    "postedDate": "2026-06-25",
    "category": "Creative"
  },
  {
    "id": "JOB-102",
    "title": "Inventory Assistant",
    "company": "Bay Trading Company",
    "description": "Recording stocks, checking inventory, updating records",
    "location": "Bay, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "inventory",
      "Excel",
      "organization",
      "record keeping"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-09-13",
    "status": "Open",
    "postedDate": "2026-06-18",
    "category": "Administrative"
  },
  {
    "id": "JOB-103",
    "title": "Online Tutor",
    "company": "Biñan Learning Center",
    "description": "Online lessons, explaining topics, preparing materials",
    "location": "Biñan, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "teaching",
      "communication",
      "patience",
      "English"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-10-03",
    "status": "Open",
    "postedDate": "2026-07-06",
    "category": "Education"
  },
  {
    "id": "JOB-104",
    "title": "Administrative Assistant",
    "company": "Los Baños Business Center",
    "description": "Document preparation, filing, data entry",
    "location": "Los Baños, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "typing",
      "Word",
      "Excel",
      "filing",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-09-06",
    "status": "Open",
    "postedDate": "2026-06-10",
    "category": "Administrative"
  },
  {
    "id": "JOB-105",
    "title": "Sales Assistant",
    "company": "Calamba Retail Store",
    "description": "Assisting customers, explaining products, processing sales",
    "location": "Calamba, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "sales",
      "communication",
      "customer service",
      "persuasion"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 1,
    "deadline": "2026-09-16",
    "status": "Open",
    "postedDate": "2026-06-07",
    "category": "Customer Service"
  },
  {
    "id": "JOB-106",
    "title": "Photo Editor",
    "company": "Santa Rosa Photo Studio",
    "description": "Editing photographs, enhancing images, organizing media",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "photography",
      "photo editing",
      "Photoshop",
      "creativity"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 2,
    "deadline": "2026-10-09",
    "status": "Open",
    "postedDate": "2026-06-12",
    "category": "Creative"
  },
  {
    "id": "JOB-107",
    "title": "Bookkeeping Assistant",
    "company": "Bay Bookkeeping Services",
    "description": "Recording transactions, organizing financial records",
    "location": "Bay, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "bookkeeping",
      "Excel",
      "organization",
      "mathematics"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-09-16",
    "status": "Open",
    "postedDate": "2026-06-22",
    "category": "Administrative"
  },
  {
    "id": "JOB-108",
    "title": "Office Assistant",
    "company": "Biñan Business Solutions",
    "description": "Email handling, encoding documents, file organization",
    "location": "Biñan, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "computer literacy",
      "typing",
      "communication",
      "email"
    ],
    "minEducation": "College Level",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-10-13",
    "status": "Open",
    "postedDate": "2026-08-01",
    "category": "Administrative"
  },
  {
    "id": "JOB-109",
    "title": "Junior Programmer",
    "company": "Los Baños Software Solutions",
    "description": "Writing basic programs, debugging, testing applications",
    "location": "Los Baños, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "programming",
      "Python",
      "Java",
      "problem solving"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-08-17",
    "status": "Open",
    "postedDate": "2026-06-08",
    "category": "Technical"
  },
  {
    "id": "JOB-110",
    "title": "Customer Support Agent",
    "company": "Calamba Support Center",
    "description": "Handling inquiries, providing support, documenting concerns",
    "location": "Calamba, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "On-site",
    "skills": [
      "customer service",
      "English",
      "communication",
      "patience"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-08-24",
    "status": "Open",
    "postedDate": "2026-06-01",
    "category": "Customer Service"
  },
  {
    "id": "JOB-111",
    "title": "Bakery Assistant",
    "company": "Santa Rosa Bakeshop",
    "description": "Baking assistance, ingredient preparation, cleaning",
    "location": "Santa Rosa, Laguna",
    "employmentType": "Part-time",
    "workArrangement": "On-site",
    "skills": [
      "baking",
      "food preparation",
      "teamwork",
      "cleanliness"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-10-15",
    "status": "Open",
    "postedDate": "2026-07-29",
    "category": "Food Service"
  },
  {
    "id": "JOB-112",
    "title": "Research Assistant",
    "company": "Bay Research Institute",
    "description": "Online research, organizing information, preparing reports",
    "location": "Bay, Laguna",
    "employmentType": "Contractual",
    "workArrangement": "On-site",
    "skills": [
      "writing",
      "research",
      "Word",
      "proofreading"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 4,
    "deadline": "2026-12-13",
    "status": "Open",
    "postedDate": "2026-08-29",
    "category": "Education"
  },
  {
    "id": "JOB-113",
    "title": "Inventory Clerk",
    "company": "Biñan Trading Company",
    "description": "Recording products, updating inventory databases, stock records",
    "location": "Biñan, Laguna",
    "employmentType": "Full-time",
    "workArrangement": "Remote",
    "skills": [
      "Excel",
      "inventory",
      "typing",
      "organization"
    ],
    "minEducation": "",
    "suitableDisabilities": [],
    "accommodations": [],
    "slots": 3,
    "deadline": "2026-08-31",
    "status": "Open",
    "postedDate": "2026-06-20",
    "category": "Administrative"
  }
]
